### ISSUE TITLE
Trailing '/' needed? Not sure if bug or a feature

### ISSUE THREAD

**Issue by AleksanderGrzybowski** [krzychukknd/moodboard#1]
```
@RestController
@RequestMapping("/v1/item")
class ItemController {
   @RequestMapping(value = "/", method = RequestMethod.GET)
   ...
```

In this version only /v1/item/ works, i was expecting /v1/item to work too, but no luck. Changing the second @RM to (value = "") makes both work, which would be better.

**Comment by AleksanderGrzybowski** [comment]
Crap now I google that and that's not obvious xD

**Comment by krzychukknd** [comment]
WONT CURVA FIX (or maybe l8er)
